name: Fix/add xref
description: Suggest a new ref or report issue about an incorrect xref.
title: '[xref] '
labels: [xref- fix or add]
assignees: kdumschott
body:
  - type: input
    id: term
    attributes:
      label: dpbo term
      description: Term name and id
      placeholder: "example term  (EXONT_00000111)"
    validations:
      required: true

  - type: textarea
    id: xref
    attributes:
      label: xref that should be added or fixed
      description: ID and label
    validations:
      required: true

  - type: textarea
    id: Comments
    attributes:
      label: Comments
      description: Please provide the reasoning for adding or fixing the xref and/or additional comments
    validations:
      required: false

  - type: input
    id: attribution
    attributes:
      label: Your nano-attribution (ORCID)
      description: If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
    validations:
      required: false
